### ISSUE TITLE
No doc available for this repository

### ISSUE THREAD

**Issue by Thecode764** [mrdoob/ui.js#6]
just read the title

**Comment by mrdoob** [comment]
No plans to document this library.

**Comment by Thecode764** [comment]
@mrdoob why?

**Comment by Pietrucci-Blacher** [comment]
Maybe the **code is too old** in this repo and there are other priorities in terms of development and it also responds in the same way as this issue was opened. There's nothing to stop you from reverse engineering and learning for yourself - it's always more interesting than waiting for documentation on a library that's only 1000 lines long and which is much than explicite☠️.
